FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y openssh-client openssh-server iputils-ping iproute2 tcpdump && \
    mkdir /var/run/sshd

RUN useradd test

CMD ["/usr/sbin/sshd", "-D"]

